# Image containing Python + Java + Spark + PG Schema Inference Project
# Use the official Python 3.14 Alpine image
FROM python:3.14-alpine

# Set environment variables to ensure Python output is not buffered
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Update package index and install OpenJDK 8 JRE + dependencies for the code
RUN apk --update add --no-cache \
    openjdk8-jre \
    yajl-dev \
    gcc \
    python3-dev \
    musl-dev \
    linux-headers


# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Install git, coreutils, procps and nano
RUN apk add --no-cache git coreutils procps nano

# Download and extract Apache Spark
ENV SPARK_VERSION=3.5.0
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
# RUN wget -q https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
#    && tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz -C /opt \
#    && mv /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME} \
#    && rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

# Set environment variables for Spark
ENV PATH=$PATH:${SPARK_HOME}/bin
ENV PYTHONPATH=${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-*.zip:$PYTHONPATH

# Clone the public GitHub repository
RUN git clone https://github.com/LEOGLLRD/PG-Schema-Inference.git pginference-fork/git

# Copy requirements 
COPY ./requirements.txt pginference-fork/
RUN  rm /app/pginference-fork/git/requirements.txt

# Create venv
RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

# Upgrade pip
RUN pip install --upgrade pip setuptools wheel

# Install deps
RUN pip install --no-cache-dir -r pginference-fork/requirements.txt

# Keep the container running
CMD ["sleep", "infinity"]   